### ISSUE TITLE
Now it throws hostname Validation errors.

### ISSUE THREAD

**Issue by karloluis** [Pupix/lol-hash-util#1]
```
stack: 'ValidationError: hostname must be string\n    
at ValidationError.Error (native)\n   
at ValidationError.CustomError (/app/node_modules/lol-riot-api-module/node_modules/expandjs/lib/error/CustomError.js:23:30)\n    
at new ValidationError (/app/node_modules/lol-riot-api-module/node_modules/expandjs/lib/error/ValidationError.js:30:21)\n    
at XPRequest.Object.defineProperty.isConstant.set [as hostname] (/app/node_modules/lol-riot-api-module/node_modules/expandjs/lib/objec
t/defineProperty.js:107:34)\n    
at XPRequest.module.exports.global.XPRequest.XP.Class.initialize.value (/app/node_modules/lol-riot-api-module/node_modules/xp-request/lib/index.js:125:34)\n    
at new Promise (/app/node_modules/lol-riot-api-module/node_modules/expa
ndjs/lib/constructors/Promise.js:55:14)\n    
at new XPRequest (eval at Class (/app/node_modules/lol-riot-api-module/node_modules/exp
andjs/lib/constructors/Class.js:62:131), <anonymous>:1:242)\n    
at RiotAPI.module.exports.XP.Class.doRequest.value [as doRequest] (/app/node_modules/lol-riot-api-module/lib/index.js:1547:31)\n    
at RiotAPI.module.exports.XP.Class.getChampionData.value (/app/node_modules/lol-riot-api-module/lib/index.js:558:22)\n    
at new Promise (/app/node_modules/lol-riot-api-module/node_modules/expandjs/lib/constructors/Promise.js:55:14)',
```

**Comment by Pupix** [comment]
I'm going to guess this is related to [lol-riot-api-module](https://github.com/Pupix/lol-riot-api-module). The problem should be fixed now. 

Sorry if there are bugs, but these are some very old modules. During the weekend I will take a look at all of them and update each one if needed.

Cheers.
